version: '3.3'

services:

  swag:
    image: linuxserver/swag
    depends_on:
      - wordpress
    volumes:
      - ./config:/config
      - ./default:/config/nginx/site-confs/default
    environment:
      - EMAIL=your-email@domain.com
      - URL=www.domain.com
      - VALIDATION=http
      - TZ=India/Kolkata
      - PUID=500
      - PGID=500
    deploy:
      mode: replicated
      replicas: 1
      labels: [APP=BLOG,SSL]
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]
    networks:
      - wp-blog 
    ports:
      - "443:443"
      - "80:80"

  wordpress:
    image: wordpress:latest
    hostname: wordpress
    restart: always
    depends_on:
      - db
    deploy:
      mode: replicated
      replicas: 1
      labels: [APP=BLOG,CMS]
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]
    networks:
      - wp-blog 
    ports:
      - "8080:80"
    volumes:
      - /var/www/html/site/wp-content:/var/www/html/wp-content
      - /var/www/html/site/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: DB_USERNAME
      WORDPRESS_DB_PASSWORD: DB_PASSWORD
      WORDPRESS_DB_NAME: DB_NAME
      WORDPRESS_CONFIG_EXTRA: |
        define( 'WP_MEMORY_LIMIT', '96M' );

  db:
    image: mysql:5.7
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    deploy:
      mode: replicated
      replicas: 1
      labels: [APP=BLOG,DB]
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]
    networks:
      - wp-blog 
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      MYSQL_USER: DB_USERNAME
      MYSQL_PASSWORD: DB_PASSWORD
      MYSQL_DATABASE: DB_NAME


networks:
  wp-blog:
